### Creating Numpy Array

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [5]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(1,11,3)

array([ 1,  4,  7, 10])

In [8]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [9]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [10]:
np.zeros([3,4],dtype='int32')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [11]:
np.random.random([2,2])

array([[0.99776326, 0.18505006],
       [0.89441471, 0.42444796]])

In [12]:
np.linspace(-10,10,5)

array([-10.,  -5.,   0.,   5.,  10.])

In [13]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attribute

In [14]:
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [15]:
a1.ndim

1

In [16]:
a2.ndim

2

In [17]:
a3.ndim

3

In [18]:
a1.dtype

dtype('int32')

In [19]:
a3.dtype

dtype('int32')

In [20]:
a2.dtype

dtype('float64')

In [21]:
print(a1.size)
print(a1)

10
[0 1 2 3 4 5 6 7 8 9]


In [22]:
print(a2.size)
print(a2)

12
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [23]:
print(a1.itemsize)
#size of datatype

4


In [24]:
print(a2.itemsize)

8


In [25]:
a1.shape

(10,)

In [26]:
a2.shape

(3, 4)

In [27]:
a3.shape

(2, 2, 2)

In [28]:
a3.dtype

dtype('int32')

In [29]:
a3.astype(np.float64)

array([[[0., 1.],
        [2., 3.]],

       [[4., 5.],
        [6., 7.]]])

### Array Operations

In [30]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [31]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [33]:
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [34]:
a2>15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [35]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [37]:
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

### Array Functions

In [38]:
a1 = np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[87., 45., 26.],
       [78., 71., 61.],
       [ 6., 47., 68.]])

In [39]:
np.max(a1)

87.0

In [40]:
np.min(a1)

6.0

In [41]:
np.sum(a1)

489.0

In [42]:
np.prod(a1)

659395413162720.0

In [43]:
np.min(a1,axis=1)

array([26., 61.,  6.])

statistical operations

In [44]:
np.mean(a1,axis=1)

array([52.66666667, 70.        , 40.33333333])

In [45]:
np.median(a1)

61.0

In [46]:
np.std(a1)

24.531159323965465

In [47]:
np.var(a1)

601.7777777777778

trignomatric functions

In [48]:
np.sin(a1)

array([[-0.82181784,  0.85090352,  0.76255845],
       [ 0.51397846,  0.95105465, -0.96611777],
       [-0.2794155 ,  0.12357312, -0.89792768]])

dot product

In [49]:
n1 = np.arange(12).reshape(3,4)
n2 = np.arange(12,24).reshape(4,3)

In [50]:
np.dot(n1,n2)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

log and exponents

In [51]:
np.log(a1)

array([[4.46590812, 3.80666249, 3.25809654],
       [4.35670883, 4.26267988, 4.11087386],
       [1.79175947, 3.8501476 , 4.21950771]])

In [52]:
np.exp(a1)

array([[6.07603023e+37, 3.49342711e+19, 1.95729609e+11],
       [7.49841700e+33, 6.83767123e+30, 3.10429794e+26],
       [4.03428793e+02, 2.58131289e+20, 3.40427605e+29]])

In [53]:
a3 = np.random.random((2,3))*100
a3

array([[49.89296312,  4.74732655, 26.36039516],
       [92.18386111, 34.14862232, 91.49642204]])

In [54]:
np.round(a3)

array([[50.,  5., 26.],
       [92., 34., 91.]])

In [55]:
np.floor(a3)

array([[49.,  4., 26.],
       [92., 34., 91.]])

In [56]:
np.ceil(a3)

array([[50.,  5., 27.],
       [93., 35., 92.]])