### Indexing

In [2]:
import numpy as np

In [3]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [4]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a1[-1]

9

In [6]:
a1[0]

0

In [7]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
a2[1,1]

5

In [9]:
a2[1,2]

6

In [10]:
a2[1,0]

4

In [11]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [12]:
a3[1,0,1]

5

In [13]:
a3[0,1,0]

2

In [14]:
a3[0,0,1]

1

In [15]:
a3[1,1,1]

7

### Slicing

In [16]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
a1[2:5]

array([2, 3, 4])

In [19]:
a1[2:5:2]

array([2, 4])

In [24]:
a1[0::3]

array([0, 3, 6, 9])

In [25]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
a2[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [29]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [30]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [33]:
a2[1,::3]

array([4, 7])

In [34]:
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [35]:
a3 = np.arange(27).reshape(3,3,3)

In [36]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [37]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [38]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [39]:
a3[0,1]

array([3, 4, 5])

In [40]:
a3[1,:,1]

array([10, 13, 16])

In [41]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [43]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

### Iterating

In [44]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [46]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [48]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [49]:
for i in np.nditer(a2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [51]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [53]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [55]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [56]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Stacking

In [57]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [58]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [59]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [60]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [61]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [65]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [66]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]