In [1]:
import numpy as np

In [2]:
a = np.random.randint(1,100,15)
a

array([56, 86, 99, 18,  8, 70, 26, 85, 37,  5, 70, 36, 60, 34, 88])

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[87, 28, 42, 95],
       [73, 39, 18, 51],
       [73, 51, 66, 86],
       [22, 27, 71, 76],
       [ 6, 34, 47, 69],
       [ 3, 40, 52,  6]])

In [4]:
np.sort(a)

array([ 5,  8, 18, 26, 34, 36, 37, 56, 60, 70, 70, 85, 86, 88, 99])

In [5]:
np.sort(b)

array([[28, 42, 87, 95],
       [18, 39, 51, 73],
       [51, 66, 73, 86],
       [22, 27, 71, 76],
       [ 6, 34, 47, 69],
       [ 3,  6, 40, 52]])

In [6]:
np.sort(a)[::-1]

array([99, 88, 86, 85, 70, 70, 60, 56, 37, 36, 34, 26, 18,  8,  5])

In [7]:
np.append(a,200)

array([ 56,  86,  99,  18,   8,  70,  26,  85,  37,   5,  70,  36,  60,
        34,  88, 200])

In [8]:
b

array([[87, 28, 42, 95],
       [73, 39, 18, 51],
       [73, 51, 66, 86],
       [22, 27, 71, 76],
       [ 6, 34, 47, 69],
       [ 3, 40, 52,  6]])

In [9]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[87.        , 28.        , 42.        , 95.        ,  0.15817145],
       [73.        , 39.        , 18.        , 51.        ,  0.25392034],
       [73.        , 51.        , 66.        , 86.        ,  0.13606263],
       [22.        , 27.        , 71.        , 76.        ,  0.74052444],
       [ 6.        , 34.        , 47.        , 69.        ,  0.80800916],
       [ 3.        , 40.        , 52.        ,  6.        ,  0.87486213]])

In [10]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

In [11]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
e = np.array([1,1,2,2,3,3,4,5,5,5,6,7,8,88,8,8,9])
np.unique(e)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 88])

In [13]:
a.shape

(15,)

In [14]:
a

array([56, 86, 99, 18,  8, 70, 26, 85, 37,  5, 70, 36, 60, 34, 88])

In [22]:
print(np.expand_dims(a,axis=0))

[[56 86 99 18  8 70 26 85 37  5 70 36 60 34 88]]


In [18]:
a

array([56, 86, 99, 18,  8, 70, 26, 85, 37,  5, 70, 36, 60, 34, 88])

In [21]:
print(np.expand_dims(a,axis=1))

[[56]
 [86]
 [99]
 [18]
 [ 8]
 [70]
 [26]
 [85]
 [37]
 [ 5]
 [70]
 [36]
 [60]
 [34]
 [88]]


In [23]:
a

array([56, 86, 99, 18,  8, 70, 26, 85, 37,  5, 70, 36, 60, 34, 88])

In [24]:
a

array([56, 86, 99, 18,  8, 70, 26, 85, 37,  5, 70, 36, 60, 34, 88])

In [25]:
np.where(a>50)

(array([ 0,  1,  2,  5,  7, 10, 12, 14], dtype=int64),)

In [26]:
np.where(a>50,25,a)

array([25, 25, 25, 18,  8, 25, 26, 25, 37,  5, 25, 36, 25, 34, 25])

In [27]:
a

array([56, 86, 99, 18,  8, 70, 26, 85, 37,  5, 70, 36, 60, 34, 88])

In [28]:
np.argmax(a)

2

In [29]:
b

array([[87, 28, 42, 95],
       [73, 39, 18, 51],
       [73, 51, 66, 86],
       [22, 27, 71, 76],
       [ 6, 34, 47, 69],
       [ 3, 40, 52,  6]])

In [31]:
np.argmax(b,axis=0)

array([0, 2, 3, 0], dtype=int64)

In [32]:
np.argmax(b,axis=1)

array([3, 0, 3, 3, 3, 2], dtype=int64)

In [33]:
np.argmin(a)

9

In [34]:
a

array([56, 86, 99, 18,  8, 70, 26, 85, 37,  5, 70, 36, 60, 34, 88])

In [35]:
np.cumsum(a)

array([ 56, 142, 241, 259, 267, 337, 363, 448, 485, 490, 560, 596, 656,
       690, 778])

In [38]:
np.cumsum(b,axis=1)

array([[ 87, 115, 157, 252],
       [ 73, 112, 130, 181],
       [ 73, 124, 190, 276],
       [ 22,  49, 120, 196],
       [  6,  40,  87, 156],
       [  3,  43,  95, 101]])

In [39]:
np.percentile(a,50)

56.0

In [43]:
np.histogram(a,bins=[0,20,40,60,80,100])

(array([3, 4, 1, 3, 4], dtype=int64), array([  0,  20,  40,  60,  80, 100]))

In [44]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])
np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

In [45]:
a

array([56, 86, 99, 18,  8, 70, 26, 85, 37,  5, 70, 36, 60, 34, 88])

In [46]:
items = [10,20,30,40,50,60,70]
np.isin(a,items)

array([False, False, False, False, False,  True, False, False, False,
       False,  True, False,  True, False, False])

In [47]:
a

array([56, 86, 99, 18,  8, 70, 26, 85, 37,  5, 70, 36, 60, 34, 88])

In [48]:
np.flip(a)

array([88, 34, 60, 36, 70,  5, 37, 85, 26, 70,  8, 18, 99, 86, 56])

In [52]:
np.flip(b,axis=1)

array([[95, 42, 28, 87],
       [51, 18, 39, 73],
       [86, 66, 51, 73],
       [76, 71, 27, 22],
       [69, 47, 34,  6],
       [ 6, 52, 40,  3]])

In [50]:
b

array([[87, 28, 42, 95],
       [73, 39, 18, 51],
       [73, 51, 66, 86],
       [22, 27, 71, 76],
       [ 6, 34, 47, 69],
       [ 3, 40, 52,  6]])

In [53]:
a

array([56, 86, 99, 18,  8, 70, 26, 85, 37,  5, 70, 36, 60, 34, 88])

In [54]:
np.put(a,[0,1],[110,530])

In [55]:
a

array([110, 530,  99,  18,   8,  70,  26,  85,  37,   5,  70,  36,  60,
        34,  88])

In [56]:
np.delete(a,[0,1])

array([99, 18,  8, 70, 26, 85, 37,  5, 70, 36, 60, 34, 88])

In [57]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

In [58]:
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [59]:
np.intersect1d(m,n)

array([3, 4, 5])

In [60]:
np.setdiff1d(m,n)

array([1, 2])

In [62]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [64]:
np.in1d(m,5)

array([False, False, False, False,  True])

In [65]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 75, 25, 25, 70, 26, 75, 37, 25, 70, 36, 60, 34, 75])